### ISSUE TITLE
Uncaught (in promise) ReferenceError: UnityLoader is not defined

### ISSUE THREAD

**Issue by meds** [jeffreylanters/react-unity-webgl#36] opened 2018-05-23 02:36 UTC
I've placed my unity files inside a webgl/ folder in my public directory, I reference them as such:

<Unity
        width="300"
        height="300"
          loader="webgl/Build/UnityLoader.js}"
          src="webgl/Build/webgltemplate.json"
        />

When I run it I get an error about 'Unexpected token <',

> Uncaught SyntaxError: Unexpected token <
> Unity.js:88 Uncaught (in promise) ReferenceError: UnityLoader is not defined
>     at eval (Unity.js:88)
> 
>   | (anonymous) | @ | Unity.js:88
> -- | -- | -- | --
>   | Promise.then (async) |   |  
>   | _instantiate | @ | Unity.js:87
>   | componentDidMount | @ | Unity.js:67
>   | (anonymous) | @ | ReactCompositeComponent.js:74
>   | measureLifeCyclePerf | @ | ReactCompositeComponent.js:13
>   | (anonymous) | @ | ReactCompositeComponent.js:74
>   | notifyAll | @ | CallbackQueue.js:31
>   | close | @ | ReactReconcileTransaction.js:34
>   | closeAll | @ | Transaction.js:119
>   | perform | @ | Transaction.js:103
>   | perform | @ | Transaction.js:99
>   | perform | @ | ReactUpdates.js:16
>   | flushBatchedUpdates | @ | ReactUpdates.js:41
>   | closeAll | @ | Transaction.js:119
>   | perform | @ | Transaction.js:103
>   | batchedUpdates | @ | ReactDefaultBatchingStrategy.js:13
>   | enqueueUpdate | @ | ReactUpdates.js:49
>   | enqueueUpdate | @ | ReactUpdateQueue.js:9
>   | enqueueSetState | @ | ReactUpdateQueue.js:72
>   | ReactComponent.setState | @ | ReactComponent.js:37
>   | handleChange | @ | connect.js:4
>   | dispatch | @ | createStore.js:80
>   | (anonymous) | @ | index.js:104
>   | (anonymous) | @ | middleware.js:5
>   | (anonymous) | @ | middleware.js:1
>   | dispatch | @ | applyMiddleware.js:16
>   | (anonymous) | @ | utils.js:5
>   | (anonymous) | @ | proc.js:99
>   | exec | @ | scheduler.js:11
>   | flush | @ | scheduler.js:20
>   | asap | @ | scheduler.js:13
>   | runPutEffect | @ | proc.js:99
>   | runEffect | @ | proc.js:93
>   | next | @ | proc.js:63
>   | currCb | @ | proc.js:71
>   | Promise.then (async) |   |  
>   | resolvePromise | @ | proc.js:95
>   | runCallEffect | @ | proc.js:102
>   | runEffect | @ | proc.js:93
>   | next | @ | proc.js:63
>   | currCb | @ | proc.js:71
>   | runSelectEffect | @ | proc.js:109
>   | runEffect | @ | proc.js:93
>   | next | @ | proc.js:63
>   | proc | @ | proc.js:46
>   | runForkEffect | @ | proc.js:105
>   | runEffect | @ | proc.js:93
>   | next | @ | proc.js:63
>   | currCb | @ | proc.js:71
>   | takeCb | @ | proc.js:95
>   | put | @ | channel.js:1
>   | (anonymous) | @ | channel.js:5
>   | (anonymous) | @ | channel.js:5
>   | exec | @ | scheduler.js:11
>   | flush | @ | scheduler.js:20
>   | asap | @ | scheduler.js:13
>   | (anonymous) | @ | channel.js:5
>   | emit | @ | channel.js:1
>   | (anonymous) | @ | middleware.js:2
>   | requestCourse | @ | index.js:239
>   | componentWillMount | @ | index.js:60
>   | proxiedMethod | @ | createPrototypeProxy.js:44
>   | (anonymous) | @ | ReactCompositeComponent.js:79
>   | measureLifeCyclePerf | @ | ReactCompositeComponent.js:13
>   | performInitialMount | @ | ReactCompositeComponent.js:79
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | _updateRenderedComponent | @ | ReactCompositeComponent.js:169
>   | _performComponentUpdate | @ | ReactCompositeComponent.js:164
>   | updateComponent | @ | ReactCompositeComponent.js:151
>   | performUpdateIfNecessary | @ | ReactCompositeComponent.js:131
>   | performUpdateIfNecessary | @ | ReactReconciler.js:56
>   | runBatchedUpdates | @ | ReactUpdates.js:37
>   | perform | @ | Transaction.js:99
>   | perform | @ | Transaction.js:99
>   | perform | @ | ReactUpdates.js:16
>   | flushBatchedUpdates | @ | ReactUpdates.js:41
>   | closeAll | @ | Transaction.js:119
>   | perform | @ | Transaction.js:103
>   | batchedUpdates | @ | ReactDefaultBatchingStrategy.js:13
>   | enqueueUpdate | @ | ReactUpdates.js:49
>   | enqueueUpdate | @ | ReactUpdateQueue.js:9
>   | enqueueSetState | @ | ReactUpdateQueue.js:72
>   | ReactComponent.setState | @ | ReactComponent.js:37
>   | update | @ | index.js:1
>   | (anonymous) | @ | index.js:1
>   | Promise.then (async) |   |  
>   | _loadModule | @ | index.js:1
>   | componentWillMount | @ | index.js:1
>   | (anonymous) | @ | ReactCompositeComponent.js:79
>   | measureLifeCyclePerf | @ | ReactCompositeComponent.js:13
>   | performInitialMount | @ | ReactCompositeComponent.js:79
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | mountChildren | @ | ReactMultiChild.js:69
>   | _createInitialChildren | @ | ReactDOMComponent.js:102
>   | mountComponent | @ | ReactDOMComponent.js:65
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | mountChildren | @ | ReactMultiChild.js:69
>   | _createInitialChildren | @ | ReactDOMComponent.js:102
>   | mountComponent | @ | ReactDOMComponent.js:65
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | performInitialMount | @ | ReactCompositeComponent.js:82
>   | mountComponent | @ | ReactCompositeComponent.js:74
>   | mountComponent | @ | ReactReconciler.js:23
>   | mountComponentIntoNode | @ | ReactMount.js:28
>   | perform | @ | Transaction.js:99
>   | batchedMountComponentIntoNode | @ | ReactMount.js:34
>   | perform | @ | Transaction.js:99
>   | batchedUpdates | @ | ReactDefaultBatchingStrategy.js:13
>   | batchedUpdates | @ | ReactUpdates.js:16
>   | _renderNewRootComponent | @ | ReactMount.js:120
>   | _renderSubtreeIntoContainer | @ | ReactMount.js:133
>   | render | @ | ReactMount.js:145
>   | ./app/app.js | @ | app.js:58
>   | __webpack_require__ | @ | bootstrap:752
>   | fn | @ | bootstrap:121
>   | 0 | @ | main.js:7455
>   | __webpack_require__ | @ | bootstrap:752
>   | (anonymous) | @ | bootstrap:872
>   | (anonymous) | @ | bootstrap:872
> 
> 

If I import loader and the webgl template like so:

```
import cba from 'webgl/Build/UnityLoader.js';
import abc from 'webgl/Build/webgltemplate.json';
```

I actually get objets back so I don't think it's about the wrong directories, I've also added images to the build folder and run them with <img src='webgl/Build/test.png />' and the image has rendered..

**Comment by jeffreylanters** [comment] 2018-05-23 08:04
Duplicate of #31

**Comment by jeffreylanters** [comment] 2018-06-03 20:31
I'm closing this issue due to inactivity, when you have any further questions or need help feel free te reopen this or a new issue.

**Closed by jeffreylanters** 2018-06-03 20:31 UTC
