### ISSUE TITLE
on "progress" not working with compressed builds

### ISSUE THREAD

**Issue by manzinge** [jeffreylanters/react-unity-webgl#180] opened 2021-04-23 13:47 UTC
**Describe the bug**
When loading a Unity Game (compressed) with the module, the unitycontext.on("progress") function does not work / does not update properly.
It will start at 0% and then jump to 90% once it is loaded (shortly after to 100%)

**To Reproduce**
1. Clone the react-unity-webgl-test repository
2. Exchange the Unity Files with a compressed Build
3. Start the App
4. Done

**Expected behavior**
It should update the progression according to the progress of the download

**Details (please complete the following information):**
 - React Unity WebGL Version: [8.2.0]
 - Device and OS: [Windows 10]
 - Browser: [Edge, Chrome, Firefox, etc.]
 - NodeJS Version: [14.0.0]

**Comment by jeffreylanters** [comment] 2021-04-23 14:47
Are you running the app locally?

**Comment by manzinge** [comment] 2021-04-23 14:50
Yes, the App is hosted locally, but the files I am trying to load are provided by an Azure App Service

**Comment by jeffreylanters** [comment] 2021-04-23 16:25
The behaviour you're describing is what happens when your app is either loaded locally or is cached. The first 90% of the progression is representing the download of the files, while the last 10% is the initialisation and start of your Unity Application.

**Comment by jeffreylanters** [comment] 2021-04-23 16:26
Could you try cleaning you cache or throttle your network speed using Chrome to see it it's still happening?

**Comment by manzinge** [comment] 2021-04-23 16:49
Thank you for your answer, I already tried clearing the cache and throttled my speed using netlimiter. But so far no success...

**Comment by manzinge** [comment] 2021-04-23 17:03
I will deploy the app onto an Azure app service and see what result I get from there. Reporting back as soon as I can!

**Comment by jeffreylanters** [comment] 2021-04-23 20:03
Okay thanks, keep me posted. I've never worked with Azure before, but you're using it just to serve the files, right? I curious if this would also happen if you'd upload your plain HTML Unity WebGL build.

**Comment by manzinge** [comment] 2021-04-24 12:55
Yes, so far I am running a react app locally and hosting the files via Azure. But I will try and host the files locally as well as the react app. If that doesn't work I will host both parts on azure and see what result I get.

**Comment by manzinge** [comment] 2021-04-25 11:49
So, I tried hosting the files locally as well as the react app (same machine) but I am still getting no proper progress on the loading. 😢 
I am also not sure what you mean by uploading the "Plain HTML Unity WebGL build". I can upload the resulting Build from Unity but it does not work as the files (brotli) can not be processed because the compressed file serving part is missing.

**Comment by jeffreylanters** [comment] 2021-04-25 22:31
It seems to be an issue caused by Unity (see link below) which has to do with the Brotli compression as you'd expected. A fix is in review but will require you to update to the latest patch.

I hope this helps you, thanks for reporting this issue. If I can help you with anything else feel free to open a new issue. 

https://issuetracker.unity3d.com/issues/webgl-incorrect-loading-progress-is-shown-in-the-player-when-build-files-are-compressed-using-brotli

**Closed by jeffreylanters** 2021-04-25 22:31 UTC

**Comment by manzinge** [comment] 2021-04-26 06:16
Alright, thank you!
I upvoted the issue as well and hope it will get fixed soon 🤞 .
