### ISSUE TITLE
error: UnityLoader[r] is not a function

### ISSUE THREAD

**Issue by YongPilMoon** [jeffreylanters/react-unity-webgl#33] opened 2018-05-14 09:49 UTC
I am trying react-unity-webgl with create-react-app.
But when i try to render Unityloader the error happend.

![error](https://image.ibb.co/mp1BMJ/error.jpg)

Do you have any idea?
I just put unity build files in public folder.
My other code is very simple.
```javascript
class App extends Component {
  render() {
    return (
      <div className="App">
        <Unity
          src="Build/UBU.json"
          loader="Build/UnityLoader.js"
        />
      </div>
    );
  }
}
```
version:
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-unity-webgl": "^6.5.0"

Thanks.

**Comment by jeffreylanters** [comment] 2018-05-14 10:12
Duplicate of #31

**Comment by YongPilMoon** [comment] 2018-05-15 01:27
Hi, Jeffery

I am sorry if it is stupid question but I think it's not the same problem with #31. 

I can refer to UnityLoader and the error happen in UnityLodader.js.

Thanks.

**Comment by jeffreylanters** [comment] 2018-05-15 08:03
Hi! No such thing as a stupid question. It seems like your React application was unable to use the UnityLoader. Can you check in your browsers inspector in the resources or network tab if the UnityLoader.js file was loaded?

**Comment by YongPilMoon** [comment] 2018-05-16 02:54
Hi! 
I checked the network tab and the file is loaded.
![error](https://preview.ibb.co/jA5mty/error1.jpg)
I still don't know why this error happen but i think It's not react-unity-webgl problem.
Becuase i tried to load unityLoader without the library but still the error happend.
Thanks.

**Comment by jeffreylanters** [comment] 2018-05-16 08:43
Ah, It could be an Unity Problem. Let me know if you've managed to fix it! Good luck.

**Closed by jeffreylanters** 2018-05-16 08:43 UTC

**Comment by marcosAJS** [comment] 2019-10-23 20:39
I have the same problem.  @jeffreylanters Did you find a solution to this problem?
