### ISSUE TITLE
When changing page, TypeError: Cannot read properties of null (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by alexisdavidson** [jeffreylanters/react-unity-webgl#406] opened 2022-07-10 15:59 UTC
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Vanilla JavaScript

### What environment are you using?

Local Development Server

### When does your problem occur?

When the Unity App quits

### What does your problem relate to?

The problem seems Unity related

### React-Unity-WebGL Version

9.0.3

### React Version

17.0.2

### Unity Version

2021.3.3f1

### What happened?

Hey there, 

The Unity Player works well and the game runs. When I change page though or hit Back for example, I get the following annoying alert error: 

Invoking error handler due to
TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
at _JS_DOM_MapViewportCoordinateToElementLocalCoordinate (http://localhost:3000/build/Build.framework.js:3:26791)
    at http://localhost:3000/build/Build.wasm:wasm-function[35601]:0x9df938
    at http://localhost:3000/build/Build.wasm:wasm-function[35507]:0x9be890
    at http://localhost:3000/build/Build.framework.js:3:203271
    at Object.mouseEventHandlerFunc [as handlerFunc] (http://localhost:3000/build/Build.framework.js:3:203307)
    at jsEventHandler (http://localhost:3000/build/Build.framework.js:3:173683)

Any idea how to get rid of that? Thank you!

### Would you be interested in contributing a fix?

- [ ] yes, I would like to contribute a fix

**Comment by jeffreylanters** [comment] 2022-07-11 12:14
Duplicate of #250

**Closed by jeffreylanters** 2022-07-11 12:14 UTC
Labels: bug
