### ISSUE TITLE
memory leak with multipaging, unload doesn't work

### ISSUE THREAD

**Issue by rn-lazuka** [jeffreylanters/react-unity-webgl#557] opened 2024-06-07 16:40 UTC
### Please avoid duplicates

- [X] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Babel and WebPack JavaScript

### What environment are you using?

Static File Serving

### When does your problem occur?

When the Unity Component unmounts

### What does your problem relate to?

The problem seems Module related

### React-Unity-WebGL Version

9.5.2

### React Version

18.2.0

### Unity Version

2022.3.19f1

### What happened?

https://github.com/jeffreylanters/react-unity-webgl/assets/58468458/cb51b3ec-690a-4525-ac0e-b9faee06ca1b
https://github.com/jeffreylanters/react-unity-webgl/assets/58468458/d63f37e1-0b22-42a1-984d-623ce6a4fc98
I have a multi-page React application, and I created a page specifically for launching all the games I have. The problem is that when I open any game, Unity gets allocated in memory. When I navigate to another page and then open the same game or any other game, a new memory slot gets allocated each time, eventually leading to lags or Unity crashing due to memory issues. I tried using the unload method, and while the logs indicate it's working, I don't see any actual memory being freed. I've resorted to reloading the page to free up memory, but is there another solution?

### Reproducible test case

Just create multipage app and try to open game few times

### Would you be interested in contributing a fix?

- [x] yes, I would like to contribute a fix

**Comment by jeffreylanters** [comment] 2024-06-11 07:59
Looks like a duplicate of #22

**Closed by jeffreylanters** 2024-06-11 07:59 UTC
Labels: bug
